export const GET_NEWS_REQUEST = 'GET_NEWS_REQUEST';
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';
export const GET_NEWS_ERROR = 'GET_NEWS_ERROR';

export const GET_NEWS_ITEM_REQUEST = 'GET_NEWS_ITEM_REQUEST';
export const GET_NEWS_ITEM_SUCCESS = 'GET_NEWS_ITEM_SUCCESS';
export const GET_NEWS_ITEM_ERROR = 'GET_NEWS_ITEM_ERROR';

export const DELETE_NEWS_ITEM_REQUEST = 'DELETE_NEWS_ITEM_REQUEST';
export const DELETE_NEWS_ITEM_ERROR = "DELETE_NEWS_ITEM_ERROR";

export const CHANGE_VALUES = 'CHANGE_VALUES';
export const ADD_FILE = 'ADD_FILE';

export const POST_FORM_REQUEST = 'POST_FORM_REQUEST';
export const POST_FORM_SUCCESS = 'POST_FORM_SUCCESS';
export const POST_FORM_ERROR = 'POST_FORM_ERROR';


export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR';

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_ERROR = 'DELETE_COMMENT_ERROR';

export const ADD_NEW_COMMENT_REQUEST = 'ADD_NEW_COMMENT_REQUEST';
export const ADD_NEW_COMMENT_SUCCESS = 'ADD_NEW_COMMENT_SUCCESS';
export const ADD_NEW_COMMENT_ERROR = 'ADD_NEW_COMMENT_ERROR';

export const CHANGE_VALUE_COMMENT = 'CHANGE_VALUE_COMMENT';