export const GET_NEWS_REQUEST = 'GET_NEWS_REQUEST';
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';
export const GET_NEWS_ERROR = 'GET_NEWS_ERROR';

export const GET_NEWS_ITEM_REQUEST = 'GET_NEWS_ITEM_REQUEST';
export const GET_NEWS_ITEM_SUCCESS = 'GET_NEWS_ITEM_SUCCESS';
export const GET_NEWS_ITEM_ERROR = 'GET_NEWS_ITEM_ERROR';